// This is automatically generated by the Tiger compiler.
// Do NOT modify!

// structures
#define true 1
#define false 0
struct LinkedList
{
  struct LinkedList_vtable *vptr;
};
struct Element
{
  struct Element_vtable *vptr;
  int Age;
  int Salary;
  int Married;
};
struct List
{
  struct List_vtable *vptr;
  struct Element * elem;
  struct List * next;
  int end;
};
struct LL
{
  struct LL_vtable *vptr;
};
// vtables structures
struct LinkedList_vtable
{
};

struct Element_vtable
{
  int (*Init)();
  int (*GetAge)();
  int (*GetSalary)();
  int (*GetMarried)();
  int (*Equal)();
  int (*Compare)();
};

struct List_vtable
{
  int (*Init)();
  int (*InitNew)();
  struct List * (*Insert)();
  int (*SetNext)();
  struct List * (*Delete)();
  int (*Search)();
  int (*GetEnd)();
  struct Element * (*GetElem)();
  struct List * (*GetNext)();
  int (*Print)();
};

struct LL_vtable
{
  int (*Start)();
};


// methods
int Element_Init(struct Element * this, int v_Age, int v_Salary, int v_Married)
{
#define Age ( this-> Age )
#define Salary ( this-> Salary )
#define Married ( this-> Married )
#define elem ( this-> elem )
#define next ( this-> next )
#define end ( this-> end )
extern struct LinkedList_vtable LinkedList_vtable_;
extern struct Element_vtable Element_vtable_;
extern struct List_vtable List_vtable_;
extern struct LL_vtable LL_vtable_;

  Age = v_Age;
  Salary = v_Salary;
  Married = v_Married;
  return true;
}
int Element_GetAge(struct Element * this)
{
#define Age ( this-> Age )
#define Salary ( this-> Salary )
#define Married ( this-> Married )
#define elem ( this-> elem )
#define next ( this-> next )
#define end ( this-> end )
extern struct LinkedList_vtable LinkedList_vtable_;
extern struct Element_vtable Element_vtable_;
extern struct List_vtable List_vtable_;
extern struct LL_vtable LL_vtable_;

  return Age;
}
int Element_GetSalary(struct Element * this)
{
#define Age ( this-> Age )
#define Salary ( this-> Salary )
#define Married ( this-> Married )
#define elem ( this-> elem )
#define next ( this-> next )
#define end ( this-> end )
extern struct LinkedList_vtable LinkedList_vtable_;
extern struct Element_vtable Element_vtable_;
extern struct List_vtable List_vtable_;
extern struct LL_vtable LL_vtable_;

  return Salary;
}
int Element_GetMarried(struct Element * this)
{
#define Age ( this-> Age )
#define Salary ( this-> Salary )
#define Married ( this-> Married )
#define elem ( this-> elem )
#define next ( this-> next )
#define end ( this-> end )
extern struct LinkedList_vtable LinkedList_vtable_;
extern struct Element_vtable Element_vtable_;
extern struct List_vtable List_vtable_;
extern struct LL_vtable LL_vtable_;

  return Married;
}
int Element_Equal(struct Element * this, struct Element * other)
{
#define Age ( this-> Age )
#define Salary ( this-> Salary )
#define Married ( this-> Married )
#define elem ( this-> elem )
#define next ( this-> next )
#define end ( this-> end )
extern struct LinkedList_vtable LinkedList_vtable_;
extern struct Element_vtable Element_vtable_;
extern struct List_vtable List_vtable_;
extern struct LL_vtable LL_vtable_;
  int ret_val;
  int aux01;
  int aux02;
  int nt;
  struct Element * x_1;
  struct Element * x_2;
  struct Element * x_3;
  struct Element * x_4;
  struct Element * x_5;
  struct Element * x_6;

  ret_val = true;
  aux01 = (x_1=other, x_1->vptr->GetAge(x_1));
  if (!((x_2=this, x_2->vptr->Compare(x_2, aux01, Age)))){
    ret_val = false;
  }
  else{
    aux02 = (x_3=other, x_3->vptr->GetSalary(x_3));
    if (!((x_4=this, x_4->vptr->Compare(x_4, aux02, Salary)))){
      ret_val = false;
    }
    else{
      if (Married){
        if (!((x_5=other, x_5->vptr->GetMarried(x_5)))){
          ret_val = false;
        }
        else{
          nt = 0;
          }
      }
      else{
        if ((x_6=other, x_6->vptr->GetMarried(x_6))){
          ret_val = false;
        }
        else{
          nt = 0;
          }
        }
      }
    }
  return ret_val;
}
int Element_Compare(struct Element * this, int num1, int num2)
{
#define Age ( this-> Age )
#define Salary ( this-> Salary )
#define Married ( this-> Married )
#define elem ( this-> elem )
#define next ( this-> next )
#define end ( this-> end )
extern struct LinkedList_vtable LinkedList_vtable_;
extern struct Element_vtable Element_vtable_;
extern struct List_vtable List_vtable_;
extern struct LL_vtable LL_vtable_;
  int retval;
  int aux02;

  retval = false;
  aux02 = num2 + 1;
  if (num1 < num2){
    retval = false;
  }
  else{
    if (!(num1 < aux02)){
      retval = false;
    }
    else{
      retval = true;
      }
    }
  return retval;
}
int List_Init(struct List * this)
{
#define Age ( this-> Age )
#define Salary ( this-> Salary )
#define Married ( this-> Married )
#define elem ( this-> elem )
#define next ( this-> next )
#define end ( this-> end )
extern struct LinkedList_vtable LinkedList_vtable_;
extern struct Element_vtable Element_vtable_;
extern struct List_vtable List_vtable_;
extern struct LL_vtable LL_vtable_;

  end = true;
  return true;
}
int List_InitNew(struct List * this, struct Element * v_elem, struct List * v_next, int v_end)
{
#define Age ( this-> Age )
#define Salary ( this-> Salary )
#define Married ( this-> Married )
#define elem ( this-> elem )
#define next ( this-> next )
#define end ( this-> end )
extern struct LinkedList_vtable LinkedList_vtable_;
extern struct Element_vtable Element_vtable_;
extern struct List_vtable List_vtable_;
extern struct LL_vtable LL_vtable_;

  end = v_end;
  elem = v_elem;
  next = v_next;
  return true;
}
struct List * List_Insert(struct List * this, struct Element * new_elem)
{
#define Age ( this-> Age )
#define Salary ( this-> Salary )
#define Married ( this-> Married )
#define elem ( this-> elem )
#define next ( this-> next )
#define end ( this-> end )
extern struct LinkedList_vtable LinkedList_vtable_;
extern struct Element_vtable Element_vtable_;
extern struct List_vtable List_vtable_;
extern struct LL_vtable LL_vtable_;
  int ret_val;
  struct List * aux03;
  struct List * aux02;
  struct List * x_7;

  aux03 = this;
  aux02 = ((struct List*)(Tiger_new (&List_vtable_, sizeof(struct List))));
  ret_val = (x_7=aux02, x_7->vptr->InitNew(x_7, new_elem, aux03, false));
  return aux02;
}
int List_SetNext(struct List * this, struct List * v_next)
{
#define Age ( this-> Age )
#define Salary ( this-> Salary )
#define Married ( this-> Married )
#define elem ( this-> elem )
#define next ( this-> next )
#define end ( this-> end )
extern struct LinkedList_vtable LinkedList_vtable_;
extern struct Element_vtable Element_vtable_;
extern struct List_vtable List_vtable_;
extern struct LL_vtable LL_vtable_;

  next = v_next;
  return true;
}
struct List * List_Delete(struct List * this, struct Element * e)
{
#define Age ( this-> Age )
#define Salary ( this-> Salary )
#define Married ( this-> Married )
#define elem ( this-> elem )
#define next ( this-> next )
#define end ( this-> end )
extern struct LinkedList_vtable LinkedList_vtable_;
extern struct Element_vtable Element_vtable_;
extern struct List_vtable List_vtable_;
extern struct LL_vtable LL_vtable_;
  struct List * my_head;
  int ret_val;
  int aux05;
  struct List * aux01;
  struct List * prev;
  int var_end;
  struct Element * var_elem;
  int aux04;
  int nt;
  struct Element * x_8;
  struct List * x_9;
  struct List * x_10;
  struct List * x_11;
  struct List * x_12;
  struct List * x_13;
  struct List * x_14;

  my_head = this;
  ret_val = false;
  aux04 = 0 - 1;
  aux01 = this;
  prev = this;
  var_end = end;
  var_elem = elem;
  while((!(var_end)) && (!(ret_val))){
    if ((x_8=e, x_8->vptr->Equal(x_8, var_elem))){
      ret_val = true;
      if (aux04 < 0){
        my_head = (x_9=aux01, x_9->vptr->GetNext(x_9));
      }
      else{
        System_out_println (0 - 555);
        aux05 = (x_10=prev, x_10->vptr->SetNext(x_10, (x_11=aux01, x_11->vptr->GetNext(x_11))));
        System_out_println (0 - 555);
        }
    }
    else{
      nt = 0;
      }
    if (!(ret_val)){
      prev = aux01;
      aux01 = (x_12=aux01, x_12->vptr->GetNext(x_12));
      var_end = (x_13=aux01, x_13->vptr->GetEnd(x_13));
      var_elem = (x_14=aux01, x_14->vptr->GetElem(x_14));
      aux04 = 1;
    }
    else{
      nt = 0;
      }
  }
  return my_head;
}
int List_Search(struct List * this, struct Element * e)
{
#define Age ( this-> Age )
#define Salary ( this-> Salary )
#define Married ( this-> Married )
#define elem ( this-> elem )
#define next ( this-> next )
#define end ( this-> end )
extern struct LinkedList_vtable LinkedList_vtable_;
extern struct Element_vtable Element_vtable_;
extern struct List_vtable List_vtable_;
extern struct LL_vtable LL_vtable_;
  int int_ret_val;
  struct List * aux01;
  struct Element * var_elem;
  int var_end;
  int nt;
  struct Element * x_15;
  struct List * x_16;
  struct List * x_17;
  struct List * x_18;

  int_ret_val = 0;
  aux01 = this;
  var_end = end;
  var_elem = elem;
  while(!(var_end)){
    if ((x_15=e, x_15->vptr->Equal(x_15, var_elem))){
      int_ret_val = 1;
    }
    else{
      nt = 0;
      }
    aux01 = (x_16=aux01, x_16->vptr->GetNext(x_16));
    var_end = (x_17=aux01, x_17->vptr->GetEnd(x_17));
    var_elem = (x_18=aux01, x_18->vptr->GetElem(x_18));
  }
  return int_ret_val;
}
int List_GetEnd(struct List * this)
{
#define Age ( this-> Age )
#define Salary ( this-> Salary )
#define Married ( this-> Married )
#define elem ( this-> elem )
#define next ( this-> next )
#define end ( this-> end )
extern struct LinkedList_vtable LinkedList_vtable_;
extern struct Element_vtable Element_vtable_;
extern struct List_vtable List_vtable_;
extern struct LL_vtable LL_vtable_;

  return end;
}
struct Element * List_GetElem(struct List * this)
{
#define Age ( this-> Age )
#define Salary ( this-> Salary )
#define Married ( this-> Married )
#define elem ( this-> elem )
#define next ( this-> next )
#define end ( this-> end )
extern struct LinkedList_vtable LinkedList_vtable_;
extern struct Element_vtable Element_vtable_;
extern struct List_vtable List_vtable_;
extern struct LL_vtable LL_vtable_;

  return elem;
}
struct List * List_GetNext(struct List * this)
{
#define Age ( this-> Age )
#define Salary ( this-> Salary )
#define Married ( this-> Married )
#define elem ( this-> elem )
#define next ( this-> next )
#define end ( this-> end )
extern struct LinkedList_vtable LinkedList_vtable_;
extern struct Element_vtable Element_vtable_;
extern struct List_vtable List_vtable_;
extern struct LL_vtable LL_vtable_;

  return next;
}
int List_Print(struct List * this)
{
#define Age ( this-> Age )
#define Salary ( this-> Salary )
#define Married ( this-> Married )
#define elem ( this-> elem )
#define next ( this-> next )
#define end ( this-> end )
extern struct LinkedList_vtable LinkedList_vtable_;
extern struct Element_vtable Element_vtable_;
extern struct List_vtable List_vtable_;
extern struct LL_vtable LL_vtable_;
  struct List * aux01;
  int var_end;
  struct Element * var_elem;
  struct Element * x_19;
  struct List * x_20;
  struct List * x_21;
  struct List * x_22;

  aux01 = this;
  var_end = end;
  var_elem = elem;
  while(!(var_end)){
    System_out_println ((x_19=var_elem, x_19->vptr->GetAge(x_19)));
    aux01 = (x_20=aux01, x_20->vptr->GetNext(x_20));
    var_end = (x_21=aux01, x_21->vptr->GetEnd(x_21));
    var_elem = (x_22=aux01, x_22->vptr->GetElem(x_22));
  }
  return true;
}
int LL_Start(struct LL * this)
{
#define Age ( this-> Age )
#define Salary ( this-> Salary )
#define Married ( this-> Married )
#define elem ( this-> elem )
#define next ( this-> next )
#define end ( this-> end )
extern struct LinkedList_vtable LinkedList_vtable_;
extern struct Element_vtable Element_vtable_;
extern struct List_vtable List_vtable_;
extern struct LL_vtable LL_vtable_;
  struct List * head;
  struct List * last_elem;
  int aux01;
  struct Element * el01;
  struct Element * el02;
  struct Element * el03;
  struct List * x_23;
  struct List * x_24;
  struct List * x_25;
  struct Element * x_26;
  struct List * x_27;
  struct List * x_28;
  struct Element * x_29;
  struct List * x_30;
  struct List * x_31;
  struct Element * x_32;
  struct List * x_33;
  struct List * x_34;
  struct Element * x_35;
  struct List * x_36;
  struct List * x_37;
  struct Element * x_38;
  struct List * x_39;
  struct List * x_40;
  struct List * x_41;
  struct List * x_42;
  struct List * x_43;
  struct List * x_44;

  last_elem = ((struct List*)(Tiger_new (&List_vtable_, sizeof(struct List))));
  aux01 = (x_23=last_elem, x_23->vptr->Init(x_23));
  head = last_elem;
  aux01 = (x_24=head, x_24->vptr->Init(x_24));
  aux01 = (x_25=head, x_25->vptr->Print(x_25));
  el01 = ((struct Element*)(Tiger_new (&Element_vtable_, sizeof(struct Element))));
  aux01 = (x_26=el01, x_26->vptr->Init(x_26, 25, 37000, false));
  head = (x_27=head, x_27->vptr->Insert(x_27, el01));
  aux01 = (x_28=head, x_28->vptr->Print(x_28));
  System_out_println (10000000);
  el01 = ((struct Element*)(Tiger_new (&Element_vtable_, sizeof(struct Element))));
  aux01 = (x_29=el01, x_29->vptr->Init(x_29, 39, 42000, true));
  el02 = el01;
  head = (x_30=head, x_30->vptr->Insert(x_30, el01));
  aux01 = (x_31=head, x_31->vptr->Print(x_31));
  System_out_println (10000000);
  el01 = ((struct Element*)(Tiger_new (&Element_vtable_, sizeof(struct Element))));
  aux01 = (x_32=el01, x_32->vptr->Init(x_32, 22, 34000, false));
  head = (x_33=head, x_33->vptr->Insert(x_33, el01));
  aux01 = (x_34=head, x_34->vptr->Print(x_34));
  el03 = ((struct Element*)(Tiger_new (&Element_vtable_, sizeof(struct Element))));
  aux01 = (x_35=el03, x_35->vptr->Init(x_35, 27, 34000, false));
  System_out_println ((x_36=head, x_36->vptr->Search(x_36, el02)));
  System_out_println ((x_37=head, x_37->vptr->Search(x_37, el03)));
  System_out_println (10000000);
  el01 = ((struct Element*)(Tiger_new (&Element_vtable_, sizeof(struct Element))));
  aux01 = (x_38=el01, x_38->vptr->Init(x_38, 28, 35000, false));
  head = (x_39=head, x_39->vptr->Insert(x_39, el01));
  aux01 = (x_40=head, x_40->vptr->Print(x_40));
  System_out_println (2220000);
  head = (x_41=head, x_41->vptr->Delete(x_41, el02));
  aux01 = (x_42=head, x_42->vptr->Print(x_42));
  System_out_println (33300000);
  head = (x_43=head, x_43->vptr->Delete(x_43, el01));
  aux01 = (x_44=head, x_44->vptr->Print(x_44));
  System_out_println (44440000);
  return 0;
}

// vtables
struct LinkedList_vtable LinkedList_vtable_ = 
{
};

struct Element_vtable Element_vtable_ = 
{
  Element_Init,
  Element_GetAge,
  Element_GetSalary,
  Element_GetMarried,
  Element_Equal,
  Element_Compare,
};

struct List_vtable List_vtable_ = 
{
  List_Init,
  List_InitNew,
  List_Insert,
  List_SetNext,
  List_Delete,
  List_Search,
  List_GetEnd,
  List_GetElem,
  List_GetNext,
  List_Print,
};

struct LL_vtable LL_vtable_ = 
{
  LL_Start,
};


// main method
int Tiger_main ()
{
  struct LL * x_0;
  System_out_println ((x_0=((struct LL*)(Tiger_new (&LL_vtable_, sizeof(struct LL)))), x_0->vptr->Start(x_0)));
}




