// This is automatically generated by the Tiger compiler.
// Do NOT modify!

// structures
#define true 1
#define false 0
struct QuickSort
{
  struct QuickSort_vtable *vptr;
};
struct QS
{
  struct QS_vtable *vptr;
  int * number;
  int size;
};
// vtables structures
struct QuickSort_vtable
{
};

struct QS_vtable
{
  int (*Start)();
  int (*Sort)();
  int (*Print)();
  int (*Init)();
};


// methods
int QS_Start(struct QS * this, int sz)
{
#define number ( this-> number )
#define size ( this-> size )
  int aux01;
  struct QS * x_1;
  struct QS * x_2;
  struct QS * x_3;
  struct QS * x_4;

  aux01 = (x_1=this, x_1->vptr->Init(x_1, sz));
  aux01 = (x_2=this, x_2->vptr->Print(x_2));
  System_out_println (9999);
  aux01 = size - 1;
  aux01 = (x_3=this, x_3->vptr->Sort(x_3, 0, aux01));
  aux01 = (x_4=this, x_4->vptr->Print(x_4));
  return 0;
}
int QS_Sort(struct QS * this, int left, int right)
{
#define number ( this-> number )
#define size ( this-> size )
  int v;
  int i;
  int j;
  int nt;
  int t;
  int cont01;
  int cont02;
  int aux03;
  struct QS * x_5;
  struct QS * x_6;

  t = 0;
  if (left < right){
    v = number[right];
    i = left - 1;
    j = right;
    cont01 = true;
    while(cont01){
      cont02 = true;
      while(cont02){
        i = i + 1;
        aux03 = number[i];
        if (!(aux03 < v)){
          cont02 = false;
        }
        else{
          cont02 = true;
          }
      }
      cont02 = true;
      while(cont02){
        j = j - 1;
        aux03 = number[j];
        if (!(v < aux03)){
          cont02 = false;
        }
        else{
          cont02 = true;
          }
      }
      t = number[i];
      number[i] = number[j];
      number[j] = t;
      if (j < i + 1){
        cont01 = false;
      }
      else{
        cont01 = true;
        }
    }
    number[j] = number[i];
    number[i] = number[right];
    number[right] = t;
    nt = (x_5=this, x_5->vptr->Sort(x_5, left, i - 1));
    nt = (x_6=this, x_6->vptr->Sort(x_6, i + 1, right));
  }
  else{
    nt = 0;
    }
  return 0;
}
int QS_Print(struct QS * this)
{
#define number ( this-> number )
#define size ( this-> size )
  int j;

  j = 0;
  while(j < size){
    System_out_println (number[j]);
    j = j + 1;
  }
  return 0;
}
int QS_Init(struct QS * this, int sz)
{
#define number ( this-> number )
#define size ( this-> size )

  size = sz;
  number = (int*)Tiger_new_array(sz);
  number[0] = 20;
  number[1] = 7;
  number[2] = 12;
  number[3] = 18;
  number[4] = 2;
  number[5] = 11;
  number[6] = 6;
  number[7] = 9;
  number[8] = 19;
  number[9] = 5;
  return 0;
}

// vtables
struct QuickSort_vtable QuickSort_vtable_ = 
{
};

struct QS_vtable QS_vtable_ = 
{
  QS_Start,
  QS_Sort,
  QS_Print,
  QS_Init,
};


// main method
int Tiger_main ()
{
  struct QS * x_0;
  System_out_println ((x_0=((struct QS*)(Tiger_new (&QS_vtable_, sizeof(struct QS)))), x_0->vptr->Start(x_0, 10)));
}




